//
//  Constants.swift
//  GraphQL-Example
//
//  Created by nicolasCombe on 8/15/21.
//

enum CountryCodes: String, CaseIterable {
    case antarctica = "AQ"
    case argentina = "AR"
    case australia = "AU"
    case brazil = "BR"
    case canada = "CA"
    case chile = "CL"
    case china = "CN"
    case colombia = "CO"
    case croatia = "HR"
    case cuba = "CU"
    case denmark = "DK"
    case egypt = "EG"
    case finland = "FI"
    case france = "FR"
    case germany = "DE"
    case greece = "GR"
    case italy = "IT"
    case jamaica = "JM"
    case japan = "JP"
    case mexico = "MX"
    case netherlands = "NL"
    case norway = "NO"
    case pakistan = "PK"
    case panama = "PA"
    case paraguay = "PY"
    case peru = "PE"
    case poland = "PL"
    case portugal = "PT"
    case russia = "RU"
    case rwanda = "RW"
    case singapore = "SG"
    case slovakia = "SK"
    case slovenia = "SI"
    case somalia = "SO"
    case spain = "ES"
    case sudan = "SD"
    case sweden = "SE"
    case switzerland = "CH"
    case thailand = "TH"
    case turkey = "TR"
    case ukraine = "UA"
    case us = "US"
    case uruguay = "UY"
    case venezuela = "VE"
    case vietnam = "VN"
}
